### PR TITLE
Refo 67

### PR DESCRIPTION
**Pull request by 10RE**

### CODE REVIEW

**Comment by makersmelx** [comment]
the function of pulling user profile is already handled in `src/models/auth.jsx`, see pullUser. 
for best practice, it would be great to use react hooks. In the current way, you will meet with huge troubles when there expected to be a page re-render.

**Review by makersmelx — CHANGES_REQUESTED** [review]
the function of pulling user profile is already handled in src/models/auth.jsx, see pullUser.
for best practice, it would be great to use react hooks. In the current way, you will meet with huge troubles when there expected to be a page re-render.

**Comment by makersmelx** [comment]
if you need to share a state using hook, refer to `useContext` document. Take the code in `src/models/auth.jsx` as example.

**Comment by 10RE** [comment]
I see, will take a look

**Pull request merged**
